apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: inc-py-cluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    volumeSize: 80
