apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: python-test
          image: 936735571533.dkr.ecr.ap-south-1.amazonaws.com/inc-ecr:latest
          ports:
            - containerPort: 8080
